{"name": "test_invalid_login", "status": "passed", "description": "Test login with incorrect email and password.", "steps": [{"name": "Attempting to log in with invalid credentials", "status": "passed", "start": 1737979937483, "stop": 1737979938563}, {"name": "Checking for error in the login response", "status": "passed", "start": 1737979938563, "stop": 1737979938563}], "attachments": [{"name": "log", "source": "37a0796c-59bf-4c34-9351-f4400aa6eb0e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "538d0314-f59f-44f7-83fe-55a02536ce5a-attachment.txt", "type": "text/plain"}], "start": 1737979937483, "stop": 1737979938564, "uuid": "cde77ea6-78e2-422f-a080-5b646d3658cb", "historyId": "27ef76719e6ec0ddbdf744d3722f4c79", "testCaseId": "27ef76719e6ec0ddbdf744d3722f4c79", "fullName": "tests.api_tests.users.test_users_api_negative#test_invalid_login", "labels": [{"name": "feature", "value": "User Authentication"}, {"name": "story", "value": "Login with Invalid Credentials"}, {"name": "parentSuite", "value": "tests.api_tests.users"}, {"name": "suite", "value": "test_users_api_negative"}, {"name": "host", "value": "Dima"}, {"name": "thread", "value": "18372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_tests.users.test_users_api_negative"}]}