{"name": "test_invalid_login", "status": "passed", "description": "Test login with incorrect email and password.", "steps": [{"name": "Attempting to log in with invalid credentials", "status": "passed", "start": 1737979453279, "stop": 1737979454299}, {"name": "Checking for error in the login response", "status": "passed", "start": 1737979454299, "stop": 1737979454299}], "attachments": [{"name": "log", "source": "da435487-5e3f-4b0e-93e4-10fb54054e6e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "615a723b-b918-4428-a36a-f4bbdd37452b-attachment.txt", "type": "text/plain"}], "start": 1737979453279, "stop": 1737979454299, "uuid": "a0f6c705-11ad-44a6-a44d-c04adf4475dc", "historyId": "27ef76719e6ec0ddbdf744d3722f4c79", "testCaseId": "27ef76719e6ec0ddbdf744d3722f4c79", "fullName": "tests.api_tests.users.test_users_api_negative#test_invalid_login", "labels": [{"name": "story", "value": "Login with Invalid Credentials"}, {"name": "feature", "value": "User Authentication"}, {"name": "parentSuite", "value": "tests.api_tests.users"}, {"name": "suite", "value": "test_users_api_negative"}, {"name": "host", "value": "Dima"}, {"name": "thread", "value": "16412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_tests.users.test_users_api_negative"}]}