{"name": "test_add_existing_user", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://thinking-tester-contact-list.herokuapp.com/users", "trace": "user_api_client = <api_clients.users_api_client.UserApiClient object at 0x0000015E642251D0>\n\n    def test_add_existing_user(user_api_client):\n        \"\"\"Test adding a user with an already used email.\"\"\"\n>       response = user_api_client.add_user(\n            first_name=\"Updated\",\n            last_name=\"Username\",\n            email=\"test2@fake.com\", # Email is already used\n            password=\"1234567890\"\n        )\n\ntests\\api_tests\\users\\test_users_api_negative.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\napi_clients\\users_api_client.py:66: in add_user\n    response.raise_for_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Response [400]>\n\n    def raise_for_status(self):\n        \"\"\"Raises :class:`HTTPError`, if one occurred.\"\"\"\n    \n        http_error_msg = \"\"\n        if isinstance(self.reason, bytes):\n            # We attempt to decode utf-8 first because some servers\n            # choose to localize their reason strings. If the string\n            # isn't utf-8, we fall back to iso-8859-1 for all other\n            # encodings. (See PR #3538)\n            try:\n                reason = self.reason.decode(\"utf-8\")\n            except UnicodeDecodeError:\n                reason = self.reason.decode(\"iso-8859-1\")\n        else:\n            reason = self.reason\n    \n        if 400 <= self.status_code < 500:\n            http_error_msg = (\n                f\"{self.status_code} Client Error: {reason} for url: {self.url}\"\n            )\n    \n        elif 500 <= self.status_code < 600:\n            http_error_msg = (\n                f\"{self.status_code} Server Error: {reason} for url: {self.url}\"\n            )\n    \n        if http_error_msg:\n>           raise HTTPError(http_error_msg, response=self)\nE           requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://thinking-tester-contact-list.herokuapp.com/users\n\nvenv\\Lib\\site-packages\\requests\\models.py:1024: HTTPError"}, "description": "Test adding a user with an already used email.", "attachments": [{"name": "log", "source": "8596455a-d2d4-4f00-9666-e46289db8760-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "66fa8792-9e29-48a1-9cd4-34adbd76394b-attachment.txt", "type": "text/plain"}], "start": 1737939462014, "stop": 1737939465313, "uuid": "861a67f7-c152-4530-a342-0d787fd381b3", "historyId": "15fae5f6a7570185997016405d02b622", "testCaseId": "15fae5f6a7570185997016405d02b622", "fullName": "tests.api_tests.users.test_users_api_negative#test_add_existing_user", "labels": [{"name": "parentSuite", "value": "tests.api_tests.users"}, {"name": "suite", "value": "test_users_api_negative"}, {"name": "host", "value": "Dima"}, {"name": "thread", "value": "20172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_tests.users.test_users_api_negative"}]}